[package]
name = "progress-bar"
version = "0.1.0"
edition = "2021"
description = "A fast progress bar in Rust similar to tqdm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
